version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app_net

  postgres:
    image: postgres:latest
    container_name: postgres-db1
    environment:
      POSTGRES_DB: contacts
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app_net

  app:
    build: .
    image: app:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  postgres-data:
